// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#ifndef _TEENSY40_LCD35_CAN3_UI_H
#define _TEENSY40_LCD35_CAN3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_version;
extern lv_obj_t *ui_uiName;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_tpcoord;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Slider1;
void ui_event_btnStart( lv_event_t * e);
extern lv_obj_t *ui_btnStart;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Switch2;
void ui_event_btnStop_Button3( lv_event_t * e);
extern lv_obj_t *ui_btnStop;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_FrameCount;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
