// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#ifndef _TEENSY40_LCD35_CAN3_UI_COMP_HOOK_H
#define _TEENSY40_LCD35_CAN3_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Button3_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
