// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#include "ui.h"

void ui_comp_Button3_create_hook( lv_obj_t * comp)
{
}
