// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#include "ui.h"


// COMPONENT Button3

lv_obj_t *ui_Button3_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button3;
cui_Button3 = lv_button_create(comp_parent);
lv_obj_set_width( cui_Button3, 100);
lv_obj_set_height( cui_Button3, 50);
lv_obj_set_x( cui_Button3, -173 );
lv_obj_set_y( cui_Button3, 118 );
lv_obj_set_align( cui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( cui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Button3, lv_color_hex(0xFF0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(cui_Button3, lv_color_hex(0xFF4040), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(cui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_Button3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON3_NUM);
children[UI_COMP_BUTTON3_BUTTON3] = cui_Button3;
lv_obj_add_event_cb(cui_Button3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button3, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Button3_create_hook(cui_Button3);
return cui_Button3; 
}

