// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void can_start(lv_event_t * e);
void can_stop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
