// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#include "ui.h"
extern bool set_can_start;
void can_start(lv_event_t * e)
{
	// Your code here
  set_can_start = 1;
}

void can_stop(lv_event_t * e)
{
	// Your code here
  set_can_start = 0;
}
