// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: teensy40_lcd35_can3

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 50 );
lv_obj_set_y( ui_Button1, 118 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_version = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_version, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_version, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_version, 180 );
lv_obj_set_y( ui_version, 87 );
lv_label_set_text(ui_version,"Version");
lv_obj_set_style_text_align(ui_version, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiName = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiName, 3 );
lv_obj_set_y( ui_uiName, -134 );
lv_obj_set_align( ui_uiName, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiName,"Teensy 4.1 LVGL Demo");
lv_obj_set_style_text_font(ui_uiName, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -2 );
lv_obj_set_y( ui_Label3, -100 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"skpang.co.uk 10/24");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -139 );
lv_obj_set_y( ui_Label4, -66 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"3.5\" LCD 480x320");

ui_tpcoord = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_tpcoord, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tpcoord, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tpcoord, 52 );
lv_obj_set_y( ui_tpcoord, 109 );
lv_label_set_text(ui_tpcoord,"TP Co Ord");
lv_obj_set_style_text_align(ui_tpcoord, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -207 );
lv_obj_set_y( ui_Label6, -43 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"TP");

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 30);
lv_obj_set_x( ui_Slider1, 124 );
lv_obj_set_y( ui_Slider1, -32 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );


//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Slider1, lv_obj_get_style_pad_right(ui_Slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_btnStart = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_btnStart, 100);
lv_obj_set_height( ui_btnStart, 50);
lv_obj_set_x( ui_btnStart, -61 );
lv_obj_set_y( ui_btnStart, 116 );
lv_obj_set_align( ui_btnStart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_btnStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnStart, lv_color_hex(0x60FA01), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 150);
lv_obj_set_height( ui_Arc1, 97);
lv_obj_set_x( ui_Arc1, -146 );
lv_obj_set_y( ui_Arc1, 40 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc1, 50);


ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 82);
lv_obj_set_height( ui_Switch1, 39);
lv_obj_set_x( ui_Switch1, 155 );
lv_obj_set_y( ui_Switch1, 20 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


ui_Switch2 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch2, 82);
lv_obj_set_height( ui_Switch2, 39);
lv_obj_set_x( ui_Switch2, 155 );
lv_obj_set_y( ui_Switch2, 67 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_btnStop = ui_Button3_create(ui_Screen1);
lv_obj_set_x( ui_btnStop, -172 );
lv_obj_set_y( ui_btnStop, 119 );

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -173 );
lv_obj_set_y( ui_Label1, 119 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"STOP");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -61 );
lv_obj_set_y( ui_Label2, 119 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"START");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -50 );
lv_obj_set_y( ui_Label5, 63 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Frame count ");

ui_FrameCount = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_FrameCount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FrameCount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FrameCount, 22 );
lv_obj_set_y( ui_FrameCount, 63 );
lv_obj_set_align( ui_FrameCount, LV_ALIGN_CENTER );
lv_label_set_text(ui_FrameCount,"0");
lv_obj_set_style_text_align(ui_FrameCount, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_btnStart, ui_event_btnStart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnStop, ui_event_btnStop_Button3, LV_EVENT_ALL, NULL);

}
